### PR TITLE
Drawer- WIP

### PR DESCRIPTION
**Pull request by anusha-66**
## In this PR:

Drawer WORK IN PROGRESS

---

## Screenshot(s):

**Before**

Drawer component didn’t exist

**After**

Drawer component:
image
image
image
image
image

---

#### Reviewer # 1

- [ ] Review **Source** code.
- [ ] Review **Test** code.
- [ ] Review **Snapshot**.
- [ ] Review PR **Storybook**.

**NOTE:** To review PR **Storybook** for the last build, **download** PR storybook from CI build **Artifacts**.

#### PR Owner

- [ ] [![Build Status][status-image]][status-url] Pipeline is green.

[status-image]: https://cd.screwdriver.cd/pipelines/3067/badge
[status-url]: https://cd.screwdriver.cd/pipelines/3067

### CODE REVIEW

**Comment by anusha-66** [comment]
@chasturansky could you please review my PR for Drawer component and approve my PR if everything looks good

**Comment by chasturansky** [comment]
A few comments. 

- Not sure how this is going to work on mobile. Usually you don't set `vh` and instead you use `top: 0, bottom: 0` This matters in safari on mobile.
- I don't see a scroll so I'm worried if you have a lot of content the page will scroll and not the content inside the drawer.
- I see margins on the story not sure if those are supposed to be there.

**Comment by chasturansky** [comment]
Additionally, its strange that there are borders on the sides where is touching the container.

**Comment by anusha-66** [comment]
@chasturansky fixed issues based on above comment in new commit 60c277b

**Comment by jazminorozco** [comment]
@anusha-66 Please remove the corner radii and border wherever the drawer meets the container. Apologies for not catching this earlier when you shared the designs over meet. Those details didn't come through when you screen shared and I'm just now seeing them.

**Comment by anusha-66** [comment]
@jazminorozco  and @chasturansky 
fixed 
No borders or Border radius from the place drawer draws  position 0 on drawer  
remove box shadows 
 drawer and accordion borders inverse : #606060
 in the commit c3cd927
 
 
image
image
image
image

**Comment by anusha-66** [comment]
Closing this Pull request to make structural drawer changes (Adding drawer container) as discussed with Chas.
will create a new PR when done

**Pull request closed without merging**
